---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MartinLai.
--- DateTime: 2018/12/12 16:10
---
local init = {
	scene = require(".MTTRoomScene");
	UserRankingData = require(".model.UserRankingData");
	MttRebuyAddonPop = require(".views.MttRebuyAddonPop");
	MttResultPop = require(".views.MttResultPop");
	MttRebuyPop = require(".views.MttRebuyPop");
	MttOtherResultPop = require(".views.MttOtherResultPop");
}

return init