---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MartinLai.
--- DateTime: 2019/3/19 15:34
---

local SpriteBlur = class("SpriteBlur", cc.Sprite)

function SpriteBlur:initWithTexture(texture, rect)
	getmetatable(self).initWithTexture(self, texture, rect)
	self:initGLProgram(cc.p(rect.width, rect.height))
end

function SpriteBlur:initGLProgram(resolution)
	local program = cc.GLProgram:createWithFilenames("shader/example_Simple.vsh", "shader/example_Blur.fsh")
	local glProgramState = cc.GLProgramState:getOrCreateWithGLProgram(program)
	
	glProgramState:setUniformVec2("resolution", resolution)
	glProgramState:setUniformFloat("blurRadius", 8)
	glProgramState:setUniformFloat("sampleNum", 8)
	
	self:setGLProgramState(glProgramState)

end

return SpriteBlur