---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MartinLai.
--- DateTime: 2018/12/12 16:10
---
local init = {
	scene = require(".NormalRoomScene");
	NormalRoomSceneCtr = require(".NormalRoomSceneCtr");
	SeatManager = require(".SeatManager");
	MatchUserOutData = require(".model.MatchUserOutData");
	TableLight = require("TableLight");
	ChipManager = require("chipManager.ChipManager");
	PropAnim = require("PropAnim");
	BuyInPop = require(".BuyInPop");
	InviteFriendPop = require(".InviteFriendPop");
	TreasureBox = require(".TreasureBox");
	TableLimit = require(".TableLimit");
}

return init