---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MartinLai.
--- DateTime: 2019/2/13 10:18
---

local InviteFriendItem = class("BlindCarryItem", cc.TableViewCell)
local BehaviorExtend = import("framework.behavior").BehaviorExtend
local BehaviorMap = import("app.common.behavior").BehaviorMap
local TrumpetSocketManager = import("app/net").TrumpetSocketManager

function InviteFriendItem:ctor()
	self:initUI()
end

function InviteFriendItem:initUI()
	self:loadLayout("creator/normalRoom/inviteFriendItem.ccreator")
	
	self.m_onLineFlag = g_NodeUtils:seekNodeByName(self, 'onLineFlag')
	self.m_headView   = g_NodeUtils:seekNodeByName(self, 'headView')
	self.m_txName     = g_NodeUtils:seekNodeByName(self, 'txName')
	self.m_txChips    = g_NodeUtils:seekNodeByName(self, 'txChips')
	self.m_btnInvite  = g_NodeUtils:seekNodeByName(self, 'btnInvite')
	self.m_txInvite   = g_NodeUtils:seekNodeByName(self, 'txInvite')

	g_NodeUtils:convertTTFToSystemFont(self.m_txName)

	BehaviorExtend(self.m_headView)
	self.m_headView:bindBehavior(BehaviorMap.HeadIconBehavior)
	
	self.m_txInvite:setString(GameString.get("str_friend_invited"))
	
	self.m_btnInvite:addClickEventListener(function()
		if not self.m_data then return end
		TrumpetSocketManager.getInstance():invitePlayGame(self.m_data.uid)
		g_AlarmTips.getInstance():setText(GameString.get("str_friend_friend_popup_invite_succ")):show()
		self.m_btnInvite:setEnabled(false)
		self.m_txInvite:setString(GameString.get("str_friend_already_invited"))
		self.m_data.alreadyInvite = true
	end)
end

function InviteFriendItem:updateCell(data)
	self.m_data = data
	local onLine = data.type ~= 3
	self.m_onLineFlag:setTexture(onLine and "creator/normalRoom/img/onLine.png" or "creator/normalRoom/img/offLine.png")
	self.m_headView:setHeadIcon(data.img)
	self.m_txName:setString(data.nick)
	self.m_txChips:setString(string.format(GameString.get("str_friend_chips"), g_MoneyUtil.formatMoney(data.money)))
	self.m_txInvite:setString(self.m_data.alreadyInvite and GameString.get("str_friend_already_invited") or GameString.get("str_friend_invited"))
	self.m_btnInvite:setEnabled(onLine and not self.m_data.alreadyInvite)
end

return InviteFriendItem