---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by CavanZhou.
--- DateTime: 2018/12/20 12:05
---

local PropAnimConfig = require(".PropAnimConfig")
local ChipManager = require("chipManager.ChipManager")
local DailyTaskManager = import("app.scenes.dailyTask").DailyTaskManager;
local PropAnim = class()


PropAnim.s_hddj_sound = {
    g_SoundMap.effect.PourWater,      g_SoundMap.effect.Hammer,         g_SoundMap.effect.Tomato,         g_SoundMap.effect.Toast,
    g_SoundMap.effect.Bomb,           g_SoundMap.effect.Kiss,           g_SoundMap.effect.Flower,         g_SoundMap.effect.Dog,
	g_SoundMap.effect.FireCracker,    g_SoundMap.effect.WineBottle,     g_SoundMap.effect.FunnyBrush,     g_SoundMap.effect.Pai,    
	g_SoundMap.effect.SprayWater,     g_SoundMap.effect.SprayWater,     g_SoundMap.effect.SprayWater,     g_SoundMap.effect.Flower,
	g_SoundMap.effect.Bomb,			  g_SoundMap.effect.Kiss,		    g_SoundMap.effect.Pai,			  g_SoundMap.effect.PourWater
};

--[Comment]
-- 发送互动道具、并播放动画
function PropAnim:playPropAnim(data,playView,fromView,toView)
	
	if not playView or not fromView or not toView then
		return
	end
	
	if data.hddjId <= 20 and  data.receiveSeatId <= 10 then
		local userData = g_Model:getData(g_ModelCmd.USER_DATA);
		local sendSeatId   = data.sendSeatId;		--发送者座位id
		local roomType = g_RoomInfo:getRoomType()
        if userData ~= nil and sendSeatId == self.selfSeatId and roomType ~= g_RoomInfo.ROOM_TYPE_TUTORIA then
--            DailyTaskManager.getInstance():reportUseProp();
        end
            
        local fPoint = self:getRelativePos(fromView,playView)
		local tPoint = self:getRelativePos(toView,playView)   
		tPoint = self:updatePoint(tPoint,data,sendSeatId)   
		
        local sendedSeatId = data.receiveSeatId;	--目标座位id,n目标作为id为9表示荷官
            
		if sendSeatId > 0 and sendedSeatId > 0 then
            
			local nomStr1 = string.format("creator/userInfo/propAtlas/hddj_%d.png",data.hddjId)
            local hddjImage      = ccui.ImageView:create(nomStr1,ccui.TextureResType.localType)
            if hddjImage ~= nil then
                hddjImage:setAnchorPoint(0.5,0.5)
                hddjImage:setScale(1.1);
				hddjImage:setPosition(fPoint.x, fPoint.y);
			end
			playView:addChild(hddjImage);
			hddjImage:setLocalZOrder(999)

			local animSprite = cc.Sprite:create()
			playView:addChild(animSprite);
			animSprite:setPosition(tPoint)
			animSprite:setVisible(false)
			animSprite:setLocalZOrder(999)

            self:moveHddj(data, hddjImage, sendedSeatId, tPoint, fPoint,animSprite);
        end
    end
end

--[Comment]
--移动互动道具
PropAnim.updatePoint = function(self,pPoint,data,sendedSeatId)
    local id = data.hddjId
    local dealerSeatId = 10;
    if id == 11 then -- 笔
		pPoint.x = pPoint.x + 30;
		pPoint.y = pPoint.y + 35;

    elseif id == 12 then -- 饼
		pPoint.x = pPoint.x - 40;
		pPoint.y = pPoint.y - 45;
		
    elseif id == 13 then -- 喷水
		pPoint.y = pPoint.y + 30;
		pPoint.x = pPoint.x + 55;
		
	end
	
	return pPoint
end

--移动互动道具
function PropAnim:moveHddj(data, hddjIcon, sendedSeatId, tPoint, fPoint,animSprite)
	local id = data.hddjId;
	local rotateList = {2,3,5,10}
	 local rList = {
		 16,17,8,10,
	  };
	  local xList = {
		  18,19,20,
	   };

	local isInTable =  function(value, tbl)
		for k,v in ipairs(tbl) do
			if v == value then
				return true;
			end
		end
		return false;
	end

	local delay = 0.05
	local mTime = 1
	local delayAction = cc.DelayTime:create(delay)
	local moveAction = cc.MoveTo:create(mTime,tPoint)
	local EasaIn = cc.EaseInOut:create(moveAction, 8)
	local callFunc = cc.CallFunc:create(function() 
		hddjIcon:removeFromParent(true)
		self:playFrameAnimation(id,animSprite)
		g_SoundManager:playEffect(PropAnim.s_hddj_sound[data.hddjId])
	end)

	local angel = cc.pGetAngle(cc.p(0,0), cc.p(tPoint.x-fPoint.x,tPoint.y-fPoint.y)) *180/math.pi

	if isInTable(id,rotateList) then -- 加旋转动画
		local an = angel>=90 and angel<=180 and -720 or 720
		local rotationAction = cc.RotateTo:create(1,an)
		local actionS = cc.Spawn:create(rotationAction,cc.Sequence:create(delayAction,EasaIn))
		hddjIcon:runAction(cc.Sequence:create(actionS,callFunc))
	else -- 旋转角度
		if id==9 then --旋转方向
			angel= angel - 45
			hddjIcon:setRotation(-angel)
		elseif isInTable(id,rList) then -- 水平翻转
			if (angel>=0 and angel<=90) or (angel>=-90 and angel<=0)  then
				hddjIcon:setFlippedX(true)
			end
		elseif isInTable(id,xList) then -- 水平翻转
			
			if (angel>90 and angel<180) or (angel>-180 and angel<-90)  then
				hddjIcon:setFlippedX(true)
			end
		end
		hddjIcon:runAction(cc.Sequence:create(delayAction,EasaIn,callFunc))
	end
end

function PropAnim:playFrameAnimation(index,node)

	local animConfig = PropAnimConfig.s_config[index]
	if animConfig==nil then
		Log.d('PropAnim:playFrameAnimation index == nil',index)
		node:setVisible(false)
		node:removeFromParent(true)
		return
	end
	local pFile = animConfig["file"]
	local imgName = animConfig["name"]
	local frameLen = animConfig.num
	local dur = animConfig.duration --- 都是2s
	dur = dur/frameLen/1000

    local cache = cc.SpriteFrameCache:getInstance()
    cache:addSpriteFrames(pFile)
	local animFrames = {}
    for i = 1,frameLen do 
		local frame = cache:getSpriteFrame( string.format(imgName, i) )
        animFrames[i] = frame
    end

    local animation = cc.Animation:createWithSpriteFrames(animFrames, dur)
	animation:setRestoreOriginalFrame(true)
	
	node:setVisible(true)
	node:setScale(1.6)
	node:runAction(cc.Sequence:create(cc.Animate:create(animation),cc.CallFunc:create(function() 
		node:setVisible(false)
		node:removeFromParent(true)
	end)))
end

function PropAnim:getRelativePos(fromNode,toNode)
	if fromNode and toNode then
		local point = fromNode:convertToWorldSpaceAR(cc.p(0,0))
		return toNode:convertToNodeSpace(point)
	end
	return nil
end

function PropAnim:playAddFriendAnim(data,playView,fromView,toView)
	if not playView or not toView then
		return
	end

	local fPoint = cc.p(0,display.height) --站起加好友
	if fromView then
		fPoint = self:getRelativePos(fromView,playView)
	end
	
	local tPoint = self:getRelativePos(toView,playView)		
	local img = ccui.ImageView:create("creator/userInfo/userInfo/room-add-friend.png",ccui.TextureResType.localType)
	playView:addChild(img);
	img:setAnchorPoint(0.5,0.5)
	img:setPosition(fPoint)
	img:setScale(0.05)
	local scaleAction2 = cc.ScaleBy:create(0.2,22,22)
	local moveAction = cc.MoveTo:create(2,tPoint)
	local scaleAction3 = cc.ScaleBy:create(0.2,0,0)
	local callfun = cc.CallFunc:create(function()
		img:removeFromParent(true)
	end)
	local EasaIn = cc.EaseInOut:create(moveAction, 8)
	local action = cc.Sequence:create(scaleAction2,EasaIn,scaleAction3,callfun)

	img:runAction(action)
end

function PropAnim:playSendChipAnim(data,playView,fromView,toView)
	if not playView or not fromView or not toView then
		return
	end
	
	local fPoint = self:getRelativePos(fromView,playView)
	local tPoint = self:getRelativePos(toView,playView)	

	local chipInfoV = 	ChipManager:takeOutChipInfos(data.sendChips)
	if not chipInfoV[1] then
		return
	end
	local spriteBg = ChipManager:getChip(chipInfoV[1].number)

    local infoLength = self.m_chipInfoV and #self.m_chipInfoV or 0;
    for i=2,infoLength do
        if (self.m_chipInfoV[i].alpha > 0.5) then
			local chip = ChipManager:getChip(self.m_chipInfoV[i].number);
			chip:setAnchorPoint(0,0):setPosition(0, 6*(i-1));
            spriteBg:addChild(chip);
        end
    end

	local spriteTexBg = cc.Sprite:create( "creator/normalRoom/img/pos/room-bet-chip-bg.png")
	spriteTexBg:setContentSize(cc.size(72,25))
	self.m_txChipNum = cc.Label:createWithSystemFont("$"..g_MoneyUtil.formatMoney(data.sendChips),"",24);
	spriteBg:addChild(spriteTexBg)
	spriteBg:addChild(self.m_txChipNum)
	spriteTexBg:setPosition(18,-10)
	self.m_txChipNum:setPosition(18,-9)
    self.m_txChipNum:setTextColor(cc.c4b(250,219,140,255))

	playView:addChild(spriteBg);
	spriteBg:setAnchorPoint(0.5,0.5)
	spriteBg:setPosition(fPoint)
	spriteBg:setScale(0.05)
	local scaleAction2 = cc.ScaleBy:create(0.2,25,25)
	local moveAction = cc.MoveTo:create(1.2,tPoint)
	local scaleAction3 = cc.ScaleBy:create(0.15,0,0)
	local callfun = cc.CallFunc:create(function()
		if spriteBg then
			spriteBg:removeFromParent(true)
		end
		g_EventDispatcher:dispatch(g_SceneEvent.SEND_CHIP_FUNISH,data)
	end)
	local EasaIn = cc.EaseInOut:create(moveAction, 8)
	local action = cc.Sequence:create(scaleAction2,EasaIn,scaleAction3,callfun)
	spriteBg:runAction(action)
end


function PropAnim:playSendGiftAnim(data,fromView,toView,seatView,playView)
	if not data or not playView or not fromView then
		return
	end

	local giftView = seatView:getGiftView()
	local giftIcon = self:getGiftIcon(data)
	local fPoint = self:getRelativePos(fromView,playView)
	local tPoint = self:getRelativePos(giftView,playView)	
	playView:addChild(giftIcon)
	giftIcon:setPosition(fPoint)	
	seatView:setGiftViewVisible(false)
	local moveAction = cc.MoveTo:create(1.3,tPoint)
	local callfun = cc.CallFunc:create(function()
		seatView:setGiftViewVisible(true)
		giftIcon:removeFromParent(true)
	end)
	local EasaIn = cc.EaseInOut:create(moveAction, 8)
	local action = cc.Sequence:create(EasaIn,callfun)
	-- giftIcon:setScale(1.7)
	giftIcon:runAction(action)
end

local BehaviorExtend = import("framework.behavior").BehaviorExtend
local BehaviorMap = import("app.common.behavior").BehaviorMap
function PropAnim:getGiftIcon(data)

	if not data.giftId then return end

	local giftView  = g_NodeUtils:getRootNodeInCreator('creator/normalRoom/giftView.ccreator')
	local giftFront = g_NodeUtils:seekNodeByName(giftView, 'giftFront')
	local gift1     = g_NodeUtils:seekNodeByName(giftView, 'giftIcon')

	gift1:setVisible(false)
	giftView:setLocalZOrder(99)
	BehaviorExtend(giftFront)
	giftFront:bindBehavior(BehaviorMap.HeadIconBehavior)

	local pre = g_AccountInfo:getGiftSWFURL()
	local map = g_Model:getData(g_ModelCmd.GIFT_ID_FILE_MAPPING)
	local url = ""
	local name = tostring(data.giftId)
	if type(pre) ~= "string" then
		pre = ""
	end
	if map and map[name] then
		url = pre .. map[name] .. ".png"
	else
		url = pre .. tostring(name) .. ".png"
	end
	giftFront:setHeadIcon(url,nil,nil,nil,nil,"creator/normalRoom/img/gift.png")
	return giftView
end

return PropAnim