---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MartinLai.
--- DateTime: 2018/12/20 12:05
---

local SeatAnim = class()

SeatAnim.seatPos = {}

function SeatAnim:play(view, tarId,callBack)
	if not view then return end
	view:stopAllActions()
	local curId = view.m_curPosId
	view:setPosition(SeatAnim.seatPos[curId].x, SeatAnim.seatPos[curId].y)
	
	local clockWise
	if (tarId > curId and (curId + 4) >= tarId) or (tarId < curId and (curId + 4 > 9) and (curId + 4) % 9 >= tarId) then
		clockWise = true
	else
		clockWise = false
	end
	--Log.d("SeatAnim:play", curId, tarId, clockWise)
	view.m_curPosId = tarId

	local anim = {}
	while curId ~= tarId do
		if clockWise then
			curId = curId + 1
			if curId == 10 then curId = 1 end
		else
			curId = curId - 1
			if curId == -1 then curId = 9 end
		end
		table.insert(anim, cc.MoveTo:create(0.2, cc.p(SeatAnim.seatPos[curId].x, SeatAnim.seatPos[curId].y)))
	end

	if type(callBack) == "function" then
		table.insert(anim, cc.CallFunc:create(callBack, {tarId}))
	end
	view:runAction(cc.Sequence:create(anim))
end

return SeatAnim